CREATE TABLE USER_APP(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
    DESCRIPTON VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    VILLE VARCHAR(50) NOT NULL,
    CONTACT VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
)

CREATE TABLE POST(
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTON VARCHAR(20) NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    REACTION JSONB NOT NULL DEFAULT '{"like": 0, "dislike": 0}'
    AUTHOR_ID INT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER_APP(ID) ON DELETE CASCADE 
)